name: snaptext_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_mlkit_text_recognition: ^0.15.0
  google_fonts: ^6.2.1
  flutter_stripe: ^11.5.0
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - .env
