// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgYz0oLPrSwiNTBz49JtpwkEwkHfOlCI',
    appId: '1:149165582495:web:a6fbd6504746ff78bd5aaa',
    messagingSenderId: '149165582495',
    projectId: 'snaptext-ai',
    authDomain: 'snaptext-ai.firebaseapp.com',
    storageBucket: 'snaptext-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWKJTKmYTVIv0y70PI6SILUxruP4c8y8k',
    appId: '1:149165582495:android:e7c5ff51f451e08cbd5aaa',
    messagingSenderId: '149165582495',
    projectId: 'snaptext-ai',
    storageBucket: 'snaptext-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6IP16pdGs8Jmx6MB5s37w7NI2-iWhtU',
    appId: '1:149165582495:ios:d7e5511fe4cb5ab1bd5aaa',
    messagingSenderId: '149165582495',
    projectId: 'snaptext-ai',
    storageBucket: 'snaptext-ai.firebasestorage.app',
    iosBundleId: 'com.example.snaptextAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6IP16pdGs8Jmx6MB5s37w7NI2-iWhtU',
    appId: '1:149165582495:ios:d7e5511fe4cb5ab1bd5aaa',
    messagingSenderId: '149165582495',
    projectId: 'snaptext-ai',
    storageBucket: 'snaptext-ai.firebasestorage.app',
    iosBundleId: 'com.example.snaptextAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgYz0oLPrSwiNTBz49JtpwkEwkHfOlCI',
    appId: '1:149165582495:web:7f11f20924cc9987bd5aaa',
    messagingSenderId: '149165582495',
    projectId: 'snaptext-ai',
    authDomain: 'snaptext-ai.firebaseapp.com',
    storageBucket: 'snaptext-ai.firebasestorage.app',
  );
}